name: qa-checks

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string

jobs:
  qa-checks:
    name: qa-checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.1
        with:
          envFilePath: ./.github/vars/global.env

      - name: Setup NodeJs ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

#      - name: Test Code
#        run: npm run test
